### ISSUE TITLE
Histogram of data returned has gaps in it.

### ISSUE THREAD

**Issue by righthalfplane** [ScrollPrize/vesuvius-c#2]
I did a histogram of the data returned and it has gaps in it ?  

![Hist](https://github.com/user-attachments/assets/a6320719-4df3-46d0-a868-80f432d8fd84)

**Comment by righthalfplane** [comment]
Exactly one half of the possible values are zero - that would be virtually impossible for real data. The scroll 1 "05000.tif" file and several others show no unused values in the 65536 values possible

**Comment by hariseldon137** [comment]
Scaffold has been rewritten, this issue should no longer persist.

**Comment by righthalfplane** [comment]
I just tried it - The problem has not been fixed.

   Dale.

**Comment by hariseldon137** [comment]
Oh great thanks for bringing this up, the issue is with the data itself. A fix was pushed but we have yet to regenerate the zarr.
